// Typed SSE client for the yvon-hermes-http wrapper on the Hostinger VPS.
// Consumed by app/api/chat/send/route.ts to stream real agent replies.
//
// Environment (Vercel env vars):
//   HERMES_URL   — e.g. https://hermes.yvon.in (set by TS-013 install.sh output)
//   HERMES_TOKEN — bearer token generated by install.sh
//
// If either env var is missing, the client returns a graceful "not configured"
// response so /api/chat/send stays on the placeholder path instead of crashing.
//
// Owner: raj · TS-013 WI-5
import type { WorkspaceKey } from './workspaces'

export interface HermesChatInput {
  message: string
  userId: string
  roomId: string
  workspace?: WorkspaceKey
  mentions?: string[]
  /** TS-025: injected real agent identity + skills (yvon-os) or venture memory (other ventures) */
  agentContext?: string
  ventureContext?: string
  /** TS-027: the 5-field input analysis (what/why/how/end/desired) for build-tier turns */
  inputAnalysis?: string
  /** Reworked 2026-08-21: dropped the Local/GitHub mode toggle — one system
   * now. Whenever the active venture has a repoUrl saved, it's always
   * forwarded, and Hermes always ensures a persistent per-venture checkout
   * is cloned/pulled and steers terminal/code_execution tools there for this
   * turn. Only ever the active venture's own configured repoUrl — never an
   * arbitrary client-supplied URL (see stream/route.ts). */
  repoUrl?: string
  /** Added 2026-08-19: the active venture's own write-scoped GitHub PAT
   * (Settings → Venture → Technical, `ventures.github_pat` in Supabase) —
   * the same credential graphify/MemPalace already use (lib/db/
   * venture-graphify.ts). Forwarded so the VPS's repo-mode clone/pull can
   * read private repos without a separate VPS-side GITHUB_PAT env var.
   * Only ever the active venture's own saved PAT — never client-supplied. */
  repoGithubPat?: string
  /** TS-018 WI-2 fix (2026-08-11): the dashboard's turn correlation, forwarded
   * so Hermes reuses it for run.started/phase.classify/phase.resolve/
   * run.completed instead of minting its own (main.py previously always
   * generated a fresh uuid4(), disconnected from every other event the turn
   * emitted — see app/api/chat/send/route.ts's header comment). */
  correlation?: string
}

/**
 * Added 2026-08-20 (usage/context indicator, Task #18): best-effort per-turn
 * usage/context metadata attached to the final `done` event — mirrors the
 * `usage` dict built in yvon-hermes-http/main.py's chat_stream.
 *
 * provider/model/toolCalls/latencyMs/turnId are server-resolved facts and
 * always populated. Token counts are NOT — hermes-agent's real AIAgent.chat()
 * return shape was never confirmed against source (run_agent.py lives only
 * on the VPS filesystem, outside this repo), so the wrapper only reports
 * them when an actual usage object was found on the agent after the turn.
 * `tokensReported: false` means "not available", not "zero" — never render
 * inputTokens/outputTokens/totalTokens as real numbers when it's false.
 *
 * contextWindow is a static best-effort lookup by model id (see
 * _CONTEXT_WINDOW_BY_MODEL in main.py) — may be stale or simply missing
 * (null) for a model not in that table; treat null the same way, as
 * "not available", not zero.
 */
export interface TurnUsage {
  provider: string | null
  model: string | null
  toolCalls: number
  latencyMs: number
  turnId: string
  tokensReported: boolean
  inputTokens: number | null
  outputTokens: number | null
  totalTokens: number | null
  contextWindow: number | null
}

/** SSE event shapes from the wrapper — mirrors yvon-hermes-http/main.py.
 *
 * TS-017 extends the schema with live status events (thinking, tool_call,
 * notice) alongside the existing token/done/error/ping events. The client
 * ignores unknown kinds gracefully.
 *
 * TS-018 WI-2: every event may carry `correlation` (one per turn) — the stream
 * route captures the first one to link the message row to its events (§5.2).
 */
export type HermesEvent = (
  | { kind: 'token'; text: string }
  | { kind: 'done'; response: string; usage?: TurnUsage }
  | { kind: 'error'; message: string }
  | { kind: 'ping' }
  // ── TS-017: live status feed ──────────────────────────────────────────────
  | { kind: 'thinking' }
  | { kind: 'tool_call.start'; toolName: string; argsPreview: string }
  | { kind: 'tool_call.end'; toolName: string; ok: boolean; summary: string }
  | { kind: 'notice'; level: string; message: string }
) & { correlation?: string }

export interface HermesConfig {
  configured: boolean
  url?: string
  token?: string
  reason?: string
}

export function hermesConfig(): HermesConfig {
  const url = process.env.HERMES_URL?.trim()
  const token = process.env.HERMES_TOKEN?.trim()
  if (!url || !token) {
    return {
      configured: false,
      reason: !url && !token
        ? 'HERMES_URL and HERMES_TOKEN not set in Vercel env'
        : !url ? 'HERMES_URL not set' : 'HERMES_TOKEN not set',
    }
  }
  return { configured: true, url, token }
}

/**
 * Ask Hermes for a full response. Awaits the entire agent turn (may include
 * multiple tool-calling iterations) and returns the concatenated text.
 *
 * Streaming variant lives in streamHermesChat() below — use that for SSE.
 */
export async function askHermes(input: HermesChatInput): Promise<
  | { ok: true; response: string; tokenCount: number }
  | { ok: false; error: string }
> {
  const cfg = hermesConfig()
  if (!cfg.configured) return { ok: false, error: cfg.reason ?? 'not configured' }

  let full = ''
  let tokenCount = 0
  try {
    for await (const event of streamHermesChat(input, cfg)) {
      if (event.kind === 'token') {
        full += event.text
        tokenCount += 1
      } else if (event.kind === 'done') {
        // Prefer the server's final "response" (includes any non-streamed tail)
        full = event.response ?? full
      } else if (event.kind === 'error') {
        return { ok: false, error: event.message }
      }
    }
    return { ok: true, response: full, tokenCount }
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) }
  }
}

/**
 * Async generator streaming SSE events from Hermes.
 * Yields token/done/error/ping events as they arrive.
 */
export async function* streamHermesChat(
  input: HermesChatInput,
  cfg?: HermesConfig,
): AsyncGenerator<HermesEvent, void, unknown> {
  const c = cfg ?? hermesConfig()
  if (!c.configured || !c.url || !c.token) {
    yield { kind: 'error', message: c.reason ?? 'not configured' }
    return
  }

  const res = await fetch(`${c.url}/v1/chat/stream`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${c.token}`,
      Accept: 'text/event-stream',
    },
    body: JSON.stringify({
      message: input.message,
      user_id: input.userId,
      room_id: input.roomId,
      workspace: input.workspace ?? undefined,
      mentions: input.mentions ?? [],
      agent_context: input.agentContext ?? undefined,
      venture_context: input.ventureContext ?? undefined,
      input_analysis: input.inputAnalysis ?? undefined,
      repo_url: input.repoUrl ?? undefined,
      github_pat: input.repoGithubPat ?? undefined,
      correlation: input.correlation ?? undefined,
    }),
  })

  if (!res.ok) {
    const body = await res.text().catch(() => '')
    yield { kind: 'error', message: `hermes ${res.status}: ${body.slice(0, 200)}` }
    return
  }

  if (!res.body) {
    yield { kind: 'error', message: 'hermes returned no body' }
    return
  }

  const reader = res.body.getReader()
  const decoder = new TextDecoder()
  let buffer = ''

  try {
    while (true) {
      const { value, done } = await reader.read()
      if (done) break
      buffer += decoder.decode(value, { stream: true })

      // SSE events end with a blank line — split on \n\n
      let sep: number
      while ((sep = buffer.indexOf('\n\n')) !== -1) {
        const raw = buffer.slice(0, sep)
        buffer = buffer.slice(sep + 2)
        // Each event has one or more "data:" lines; concat them.
        const dataLines = raw
          .split('\n')
          .filter((l) => l.startsWith('data:'))
          .map((l) => l.slice(5).trim())
          .join('')
        if (!dataLines) continue
        try {
          const parsed = JSON.parse(dataLines) as HermesEvent
          yield parsed
          if (parsed.kind === 'done' || parsed.kind === 'error') return
        } catch {
          // ignore malformed events
        }
      }
    }
  } finally {
    try {
      reader.releaseLock()
    } catch {
      // best-effort cleanup
    }
  }
}
