// Typed SSE client for the yvon-hermes-http wrapper on the Hostinger VPS.
// Consumed by app/api/chat/send/route.ts to stream real agent replies.
//
// Environment (Vercel env vars):
//   HERMES_URL   — e.g. https://hermes.yvon.in (set by TS-013 install.sh output)
//   HERMES_TOKEN — bearer token generated by install.sh
//
// If either env var is missing, the client returns a graceful "not configured"
// response so /api/chat/send stays on the placeholder path instead of crashing.
//
// Owner: raj · TS-013 WI-5
import type { WorkspaceKey } from './workspaces'

export interface HermesChatInput {
  message: string
  userId: string
  roomId: string
  workspace?: WorkspaceKey
  mentions?: string[]
  /** TS-025: injected real agent identity + skills (yvon-os) or venture memory (other ventures) */
  agentContext?: string
  ventureContext?: string
  /** TS-027: the 5-field input analysis (what/why/how/end/desired) for build-tier turns */
  inputAnalysis?: string
  /** Repo-mode toggle (2026-08-11): 'github' + repoUrl tells the VPS agent to
   * clone/pull that repo and steer its terminal/code_execution tools there
   * for this turn, instead of its default local working directory. Only
   * ever the active venture's own configured repoUrl — never an arbitrary
   * client-supplied URL (see RepoModeToggle.tsx / stream/route.ts). */
  repoMode?: 'local' | 'github'
  repoUrl?: string
}

/** SSE event shapes from the wrapper — mirrors yvon-hermes-http/main.py.
 *
 * TS-017 extends the schema with live status events (thinking, tool_call,
 * notice) alongside the existing token/done/error/ping events. The client
 * ignores unknown kinds gracefully.
 *
 * TS-018 WI-2: every event may carry `correlation` (one per turn) — the stream
 * route captures the first one to link the message row to its events (§5.2).
 */
export type HermesEvent = (
  | { kind: 'token'; text: string }
  | { kind: 'done'; response: string }
  | { kind: 'error'; message: string }
  | { kind: 'ping' }
  // ── TS-017: live status feed ──────────────────────────────────────────────
  | { kind: 'thinking' }
  | { kind: 'tool_call.start'; toolName: string; argsPreview: string }
  | { kind: 'tool_call.end'; toolName: string; ok: boolean; summary: string }
  | { kind: 'notice'; level: string; message: string }
) & { correlation?: string }

export interface HermesConfig {
  configured: boolean
  url?: string
  token?: string
  reason?: string
}

export function hermesConfig(): HermesConfig {
  const url = process.env.HERMES_URL?.trim()
  const token = process.env.HERMES_TOKEN?.trim()
  if (!url || !token) {
    return {
      configured: false,
      reason: !url && !token
        ? 'HERMES_URL and HERMES_TOKEN not set in Vercel env'
        : !url ? 'HERMES_URL not set' : 'HERMES_TOKEN not set',
    }
  }
  return { configured: true, url, token }
}

/**
 * Ask Hermes for a full response. Awaits the entire agent turn (may include
 * multiple tool-calling iterations) and returns the concatenated text.
 *
 * Streaming variant lives in streamHermesChat() below — use that for SSE.
 */
export async function askHermes(input: HermesChatInput): Promise<
  | { ok: true; response: string; tokenCount: number }
  | { ok: false; error: string }
> {
  const cfg = hermesConfig()
  if (!cfg.configured) return { ok: false, error: cfg.reason ?? 'not configured' }

  let full = ''
  let tokenCount = 0
  try {
    for await (const event of streamHermesChat(input, cfg)) {
      if (event.kind === 'token') {
        full += event.text
        tokenCount += 1
      } else if (event.kind === 'done') {
        // Prefer the server's final "response" (includes any non-streamed tail)
        full = event.response ?? full
      } else if (event.kind === 'error') {
        return { ok: false, error: event.message }
      }
    }
    return { ok: true, response: full, tokenCount }
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) }
  }
}

/**
 * Async generator streaming SSE events from Hermes.
 * Yields token/done/error/ping events as they arrive.
 */
export async function* streamHermesChat(
  input: HermesChatInput,
  cfg?: HermesConfig,
): AsyncGenerator<HermesEvent, void, unknown> {
  const c = cfg ?? hermesConfig()
  if (!c.configured || !c.url || !c.token) {
    yield { kind: 'error', message: c.reason ?? 'not configured' }
    return
  }

  const res = await fetch(`${c.url}/v1/chat/stream`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${c.token}`,
      Accept: 'text/event-stream',
    },
    body: JSON.stringify({
      message: input.message,
      user_id: input.userId,
      room_id: input.roomId,
      workspace: input.workspace ?? undefined,
      mentions: input.mentions ?? [],
      agent_context: input.agentContext ?? undefined,
      venture_context: input.ventureContext ?? undefined,
      input_analysis: input.inputAnalysis ?? undefined,
      repo_mode: input.repoMode ?? undefined,
      repo_url: input.repoUrl ?? undefined,
    }),
  })

  if (!res.ok) {
    const body = await res.text().catch(() => '')
    yield { kind: 'error', message: `hermes ${res.status}: ${body.slice(0, 200)}` }
    return
  }

  if (!res.body) {
    yield { kind: 'error', message: 'hermes returned no body' }
    return
  }

  const reader = res.body.getReader()
  const decoder = new TextDecoder()
  let buffer = ''

  try {
    while (true) {
      const { value, done } = await reader.read()
      if (done) break
      buffer += decoder.decode(value, { stream: true })

      // SSE events end with a blank line — split on \n\n
      let sep: number
      while ((sep = buffer.indexOf('\n\n')) !== -1) {
        const raw = buffer.slice(0, sep)
        buffer = buffer.slice(sep + 2)
        // Each event has one or more "data:" lines; concat them.
        const dataLines = raw
          .split('\n')
          .filter((l) => l.startsWith('data:'))
          .map((l) => l.slice(5).trim())
          .join('')
        if (!dataLines) continue
        try {
          const parsed = JSON.parse(dataLines) as HermesEvent
          yield parsed
          if (parsed.kind === 'done' || parsed.kind === 'error') return
        } catch {
          // ignore malformed events
        }
      }
    }
  } finally {
    try {
      reader.releaseLock()
    } catch {
      // best-effort cleanup
    }
  }
}
