#!/usr/bin/env bash
# deploy-open-design.sh — provision nexu-io/open-design (the daemon behind
# Stage 2's live reference tier + Stage 5b's future skill/design-system
# grounding) on the Contabo VPS, docs/PRD-design-first-workflow.md.
#
# Verified against a real clone of github.com/nexu-io/open-design (not
# guessed) before writing this:
#   - Runtime is a single Docker container (Node 24 Alpine), NOT the
#     poetry/pnpm build dance screenshot-to-code needed. deploy/docker-
#     compose.yml pulls a prebuilt image (ghcr.io/nexu-io/od:latest) by
#     default — this script pulls it explicitly before `up` so it never
#     falls back to building the 386MB monorepo locally.
#   - Idle RAM is documented by the project itself (deploy/.env.example)
#     as ~18-22 MiB; default mem_limit is 384m.
#   - Port 7456, bound 127.0.0.1-only in the shipped compose file — same
#     loopback-only discipline as yvon-hermes-dashboard.service and
#     yvon-screenshot-to-code.service. Nothing here changes that.
#   - Auth: OD_API_TOKEN (openssl rand -hex 32) is generated by this
#     script, not invented/hardcoded. The alternative
#     (OPEN_DESIGN_DISABLE_API_AUTH=1) is deliberately NOT set here —
#     same "don't loosen a default without being asked" stance as every
#     other service file in vps-scripts/.
#   - Image-generation providers (OpenAI/Nano Banana/OpenRouter/etc. — see
#     docs/PRD-design-first-workflow.md's OpenRouter blueprint section)
#     are NOT configured by this script. Confirmed against real source
#     (apps/daemon/src/media/index.ts) that generate_image/video/speech
#     fail loud with a clear "provider not configured" 503 when none are
#     set — never a silent stub in a release build (OD_MEDIA_ALLOW_STUBS
#     defaults off). Safe to deploy with zero image providers configured.
#
# Only the deploy/ subtree is pulled (sparse + blob:none filter) — the
# full repo is 386MB of monorepo source this VPS doesn't need just to run
# the prebuilt image.
#
# Run on the box:
#   scp vps-scripts/deploy-open-design.sh root@169.58.107.148:/root/
#   ssh root@169.58.107.148 'bash /root/deploy-open-design.sh'
# ---------------------------------------------------------------------------
set -euo pipefail

BASE=/opt/yvon-tools
APP_DIR="$BASE/open-design-deploy"
PORT="${OPEN_DESIGN_PORT:-7456}"

echo "▸ 1/5  Docker + compose plugin…"
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sh
fi
systemctl enable --now docker
if ! docker compose version >/dev/null 2>&1; then
  apt-get update -qq
  apt-get install -y -qq docker-compose-plugin
fi

echo "▸ 2/5  fetch deploy/ only (sparse checkout, not the full 386MB repo)…"
mkdir -p "$BASE"
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" pull --ff-only
else
  git clone --filter=blob:none --depth 1 --sparse \
    https://github.com/nexu-io/open-design.git "$APP_DIR"
  ( cd "$APP_DIR" && git sparse-checkout set deploy )
fi

echo "▸ 3/5  .env (OD_API_TOKEN generated fresh, nothing else invented)…"
ENV_FILE="$APP_DIR/deploy/.env"
if [ ! -f "$ENV_FILE" ]; then
  cp "$APP_DIR/deploy/.env.example" "$ENV_FILE"
  TOKEN="$(openssl rand -hex 32)"
  # portable sed -i (BSD/GNU) — this box is Debian so GNU sed, but keep it
  # explicit rather than assuming.
  sed -i "s|^OD_API_TOKEN=.*|OD_API_TOKEN=$TOKEN|" "$ENV_FILE"
  sed -i "s|^OPEN_DESIGN_PORT=.*|OPEN_DESIGN_PORT=$PORT|" "$ENV_FILE"
  echo "  wrote $ENV_FILE with a fresh OD_API_TOKEN — save it, it's not printed again below"
else
  echo "  $ENV_FILE already exists — leaving it as-is"
fi

echo "▸ 4/5  pull the prebuilt image explicitly (skip a local 386MB build)…"
( cd "$APP_DIR/deploy" && docker compose pull )

echo "▸ 5/5  up…"
( cd "$APP_DIR/deploy" && docker compose up -d )

echo ""
echo "▸ health check…"
sleep 3
curl -fsS "http://127.0.0.1:$PORT/api/health" && echo "" || echo "  (not answering yet — check: docker compose -f $APP_DIR/deploy/docker-compose.yml logs)"

echo ""
echo "Next steps (manual, not run by this script):"
echo "  1. OD_API_TOKEN is in $ENV_FILE — cli/lib/open_design_client.py will need it"
echo "     wherever cli/design.py runs (env var, same convention as SCREENSHOT_TO_CODE_URL)."
echo "  2. Loopback-only by default (127.0.0.1:$PORT) — proxy it the same way as the other"
echo "     yvon-*.service units if something outside this box needs to reach it."
echo "  3. No image/video/speech provider is configured (OpenAI/Nano Banana/OpenRouter/etc.)."
echo "     generate_image and friends will return a clear 503 'not configured' until you set"
echo "     one via the daemon's PUT /api/media/config or an OD_<PROVIDER>_API_KEY env var in"
echo "     $ENV_FILE — deliberately not automated here, same as screenshot-to-code's keys."
echo "  4. Point OPEN_DESIGN_URL at http://127.0.0.1:$PORT from wherever cli/design.py runs —"
echo "     Stage 2's live tier (F2a) degrades to curated-only when this isn't reachable/set."
