// src/adapters/config.ts — Engine configuration resolver
//
// All paths are resolved from yvon.config.json (generated by yvon init)
// or from environment variables. No hardcoded paths.

import { homedir } from 'os'
import { resolve, join } from 'path'
import { existsSync, readFileSync } from 'fs'

export interface EngineConfig {
  // Project paths
  projectRoot: string
  teamsPath: string
  sharedOsPath: string
  booksPath: string
  graphifyReport: string
  graphifyGraphJson: string
  codegraphReport: string
  agentMemoryDir: string
  hermesMemoryDir: string
  projectClaudePath: string
  ventureDocsDir: string
  sessionMemoryDir: string

  // CIE settings
  cieEnabled: boolean
  contextCap: number
  adaptiveInjection: boolean
  toonPreferCompressed: boolean
  citationInjection: boolean
  pipelineOrchestration: boolean

  // TOON settings
  toonEnabled: boolean
  toonBidirectional: boolean
}

let cachedConfig: EngineConfig | null = null
let configMtime: number = 0

function detectProjectRoot(): string {
  // Walk up from cwd to find yvon.config.json or package.json
  let dir = process.cwd()
  for (let i = 0; i < 10; i++) {
    if (existsSync(join(dir, 'yvon.config.json'))) return dir
    if (existsSync(join(dir, 'package.json'))) return dir
    const parent = resolve(dir, '..')
    if (parent === dir) break
    dir = parent
  }
  return process.cwd()
}

export function getConfig(): EngineConfig {
  const root = detectProjectRoot()
  const configPath = join(root, 'yvon.config.json')
  
  // Try reading config file
  let fileConfig: Partial<EngineConfig> = {}
  if (existsSync(configPath)) {
    try {
      fileConfig = JSON.parse(readFileSync(configPath, 'utf-8'))
    } catch { /* use defaults */ }
  }

  // Relative paths in yvon.config.json resolve against project root (portable,
  // in-repo config); absolute paths pass through unchanged.
  const fromRoot = (p: string | undefined): string | undefined =>
    p === undefined ? undefined : (resolve(p) === p ? p : join(root, p))

  return {
    projectRoot: root,
    teamsPath: fromRoot(fileConfig.teamsPath) ?? join(root, 'Teams'),
    sharedOsPath: fromRoot(fileConfig.sharedOsPath) ?? join(root, 'Teams', 'Shared OS', 'logical'),
    booksPath: fromRoot(fileConfig.booksPath) ?? join(root, 'Books'),
    graphifyReport: fromRoot(fileConfig.graphifyReport) ?? join(root, 'graphify-out', 'GRAPH_REPORT.md'),
    graphifyGraphJson: fromRoot(fileConfig.graphifyGraphJson) ?? join(root, 'graphify-out', 'graph.json'),
    codegraphReport: fromRoot(fileConfig.codegraphReport) ?? join(root, 'graphify-out', 'CODEGRAPH_REPORT.md'),
    agentMemoryDir: fromRoot(fileConfig.agentMemoryDir) ?? join(root, 'agent-memory'),
    hermesMemoryDir: fromRoot(fileConfig.hermesMemoryDir) ?? join(homedir(), '.hermes', 'memories'),
    projectClaudePath: fromRoot(fileConfig.projectClaudePath) ?? join(root, 'CLAUDE.md'),
    ventureDocsDir: fromRoot(fileConfig.ventureDocsDir) ?? join(root, 'docs', 'ventures'),
    sessionMemoryDir: fromRoot(fileConfig.sessionMemoryDir) ?? join(root, 'store', 'sessions'),

    cieEnabled: fileConfig.cieEnabled ?? true,
    contextCap: fileConfig.contextCap ?? 2500,
    adaptiveInjection: fileConfig.adaptiveInjection ?? true,
    toonPreferCompressed: fileConfig.toonPreferCompressed ?? true,
    citationInjection: fileConfig.citationInjection ?? true,
    pipelineOrchestration: fileConfig.pipelineOrchestration ?? true,

    toonEnabled: fileConfig.toonEnabled ?? true,
    toonBidirectional: fileConfig.toonBidirectional ?? true,
  }
}

export function invalidateConfig(): void {
  cachedConfig = null
}
