"""events.py — emit run lifecycle events to the Supabase event log.

Architecture §5.4: append-only `events` table. The dashboard (on Vercel) cannot
hold a live connection, so it subscribes to Supabase Realtime directly; this
process only makes OUTBOUND writes. No inbound ports, no tunnel.

HARD RULE: emitting must never block or fail an agent run. Every call is
fire-and-forget on a background thread with all exceptions swallowed and logged.

Config (env, set in the systemd unit — never committed):
    SUPABASE_URL                 https://<ref>.supabase.co
    SUPABASE_SERVICE_ROLE_KEY    service role key (server-side only)
    YVON_EVENTS_ENABLED          '0' disables emission entirely (default on)
"""
from __future__ import annotations

import json
import logging
import os
import threading
import urllib.request
from typing import Any, Optional

log = logging.getLogger("yvon.events")

_URL = os.environ.get("SUPABASE_URL", "").rstrip("/")
_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")
_ENABLED = os.environ.get("YVON_EVENTS_ENABLED", "1") != "0" and bool(_URL and _KEY)

# agent name → structure.json id (e.g. 'mia' → 'engineering-mia').
# Generated by scripts/build-structure.mjs; all 46 agent names are unique, so the
# mapping is 1:1. Unknown actors are emitted verbatim AND logged, so a drifted id
# fails loudly in the log instead of silently never lighting a node.
_ALIAS_PATH = os.environ.get("YVON_AGENT_ALIAS_PATH", "/opt/yvon-hermes-http/agent-alias.json")
try:
    with open(_ALIAS_PATH, "r", encoding="utf-8") as fh:
        _ALIAS: dict[str, str] = json.load(fh)
except Exception:  # noqa: BLE001 — absent map is fine; ids pass through
    _ALIAS = {}


def resolve_actor(name: str) -> str:
    """Map a bare agent name to its stable structure id. Logs unknowns loudly."""
    if not name:
        return ""
    key = name.lstrip("@").strip()
    hit = _ALIAS.get(key)
    if hit:
        return hit
    if _ALIAS:  # a map exists but this name isn't in it → drift
        log.warning("events: unknown agent '%s' — not in %s; node will not light", key, _ALIAS_PATH)
    return key


def _post(row: dict[str, Any]) -> None:
    try:
        req = urllib.request.Request(
            f"{_URL}/rest/v1/events",
            data=json.dumps(row).encode(),
            headers={
                "Content-Type": "application/json",
                "apikey": _KEY,
                "Authorization": f"Bearer {_KEY}",
                "Prefer": "return=minimal",
            },
            method="POST",
        )
        urllib.request.urlopen(req, timeout=4).close()
    except Exception as exc:  # noqa: BLE001 — never let telemetry break a run
        log.debug("events: emit failed (ignored): %s", exc)


def emit(
    kind: str,
    actor: str,
    context_id: Optional[str] = None,
    correlation: Optional[str] = None,
    **payload: Any,
) -> None:
    """Fire-and-forget one event. Returns immediately; never raises."""
    if not _ENABLED or not kind:
        return
    row = {
        "source": "hermes",
        "context_id": context_id or "yvon-os",
        "kind": kind,
        "actor": resolve_actor(actor) or "system",
        "payload": payload or {},
    }
    if correlation:
        row["correlation"] = correlation
    threading.Thread(target=_post, args=(row,), daemon=True).start()
