// lib/cie/sources/venture-agents.ts — Venture agent-grant registry (Supabase `venture_agents`)
//
// system-harness/graph-brain/GRAPH-BRAIN-DESIGN.md §16.3/§23.3: "Onboarding a client is one row in `ventures` + grant
// rows... upgrading a client is editing that list, expanded into `venture_agents` rows at write
// time." The table itself was proposed in system-harness/graph-brain/YVON-GRAPH.md §1.3 ("the one genuinely new
// table") but never actually created until 2026-08-09 — see
// dashboard/supabase/migrations/111_venture_agents_and_tier.sql for the full writeup, discussed
// and confirmed with the operator before building (backfill-all-46 + auto-sync approach, tier
// column added in the same pass, no runtime enforcement wired yet — schema + backfill only).
//
// AUTO-SYNC, not a one-time backfill: the operator explicitly asked for this to keep itself
// current as new agents are added, not require a manual re-run of a hardcoded list. This module
// reads the LIVE agent roster from dashboard/public/structure.json (regenerated by
// scripts/build-structure.mjs from Teams/ — the actual source of truth) every time it runs, so
// there is nothing here to update when agent #47 is added — re-running syncVentureAgents() is
// the entire "automatic" mechanism. Only applies to kind='core' ventures (Novizio today) — a
// 'venture' or 'client' tenant's grants are an onboarding-time decision (per §23.3's "team"
// preset language), not something this function should silently expand.
//
// UNVERIFIED END-TO-END, same flag as sources/ventures.ts: this sandbox has no fetch() egress to
// *.supabase.co, so syncVentureAgents()'s actual HTTP round trip couldn't be exercised here. What
// WAS verified live (via the Supabase MCP's separate network path, 2026-08-09): the table schema,
// RLS policies, and a manual SQL-equivalent backfill (46 rows for novizio, matching this
// function's exact logic — same roster source, same primary key, same ON CONFLICT DO NOTHING
// idempotency). Re-verify this module's actual fetch() path the first time it runs somewhere
// with real egress to Supabase.

import { readFileSync, existsSync } from 'fs'
import { join } from 'path'
import { getConfig } from '../../adapters/config'
import { listVentures } from './ventures'

export interface StructureAgent {
  id: string   // e.g. 'brand-studio-atlas' — dept-slug-agent-name, per structure.json
  name: string
}

function supabaseEnv(): { url: string; key: string } | null {
  const url = process.env.SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !key) return null
  return { url, key }
}

/**
 * getRealAgentRoster — reads the live, regenerated structure.json rather than hardcoding a count
 * or list anywhere. This IS the "auto-update as agents are added" mechanism: there's no stored
 * agent list in this module to go stale.
 */
export function getRealAgentRoster(): StructureAgent[] {
  const path = join(getConfig().projectRoot, 'dashboard', 'public', 'structure.json')
  if (!existsSync(path)) return []
  try {
    const data = JSON.parse(readFileSync(path, 'utf-8')) as {
      departments: { agents: { id: string; name: string }[] }[]
    }
    return data.departments.flatMap((d) => d.agents.map((a) => ({ id: a.id, name: a.name })))
  } catch {
    return []
  }
}

export interface VentureAgentRow {
  ventureSlug: string
  agentId: string
  enabled: boolean
}

async function fetchExistingGrants(ventureSlug: string): Promise<Set<string>> {
  const env = supabaseEnv()
  if (!env) return new Set()
  try {
    const res = await fetch(
      `${env.url}/rest/v1/venture_agents?select=agent_id&venture_slug=eq.${encodeURIComponent(ventureSlug)}`,
      { headers: { apikey: env.key, Authorization: `Bearer ${env.key}` } },
    )
    if (!res.ok) return new Set()
    const rows = (await res.json()) as { agent_id: string }[]
    return new Set(rows.map((r) => r.agent_id))
  } catch {
    return new Set()
  }
}

async function insertGrants(ventureSlug: string, agentIds: string[]): Promise<{ inserted: number; error?: string }> {
  if (agentIds.length === 0) return { inserted: 0 }
  const env = supabaseEnv()
  if (!env) return { inserted: 0, error: 'SUPABASE_URL/SUPABASE_SERVICE_ROLE_KEY not set' }
  try {
    const rows = agentIds.map((agentId) => ({
      venture_slug: ventureSlug,
      agent_id: agentId,
      enabled: true,
      granted_by: 'syncVentureAgents (auto, core venture)',
    }))
    const res = await fetch(`${env.url}/rest/v1/venture_agents`, {
      method: 'POST',
      headers: {
        apikey: env.key,
        Authorization: `Bearer ${env.key}`,
        'Content-Type': 'application/json',
        Prefer: 'resolution=ignore-duplicates,return=minimal',
      },
      body: JSON.stringify(rows),
    })
    if (!res.ok) return { inserted: 0, error: `${res.status} ${await res.text()}` }
    return { inserted: agentIds.length }
  } catch (err) {
    return { inserted: 0, error: (err as Error).message }
  }
}

export interface SyncResult {
  ventureSlug: string
  totalRealAgents: number
  alreadyGranted: number
  newlyGranted: string[]
  error?: string
}

/**
 * syncVentureAgents — for every kind='core' venture, grant any real agent (from the live
 * structure.json roster) that doesn't already have a venture_agents row. Never revokes — an
 * agent removed from Teams/ still has its historical grant row; that's a separate, deliberate
 * decision this function doesn't make. Safe to re-run anytime (idempotent — only inserts missing
 * rows, `resolution=ignore-duplicates` on the primary key handles races).
 */
export async function syncVentureAgents(): Promise<SyncResult[]> {
  const roster = getRealAgentRoster()
  const ventures = await listVentures({ skipCache: true })
  const coreVentures = ventures.filter((v) => v.kind === 'core')

  const results: SyncResult[] = []
  for (const venture of coreVentures) {
    const existing = await fetchExistingGrants(venture.slug)
    const missing = roster.map((a) => a.id).filter((id) => !existing.has(id))
    const { inserted, error } = await insertGrants(venture.slug, missing)
    results.push({
      ventureSlug: venture.slug,
      totalRealAgents: roster.length,
      alreadyGranted: existing.size,
      newlyGranted: error ? [] : missing.slice(0, inserted),
      error,
    })
  }
  return results
}
