// /brain — Graph Memory. Embeds graphify's REAL interactive graph of the whole repo
// (all 7.4k nodes / 15.8k edges / 415 communities) — its own WebGL viz with built-in
// click / filter / search / community coloring. This is the detailed graph, not an
// aggregate. Generated by: graphify cluster-only . --no-label  → cli/graph-sync.sh
// copies graphify-out/graph.html → public/. Owner: mia · G-track.
'use client'

import { useEffect, useState } from 'react'
import { PageHeader } from '@/components/ui'

export default function BrainPage() {
  const [ok, setOk] = useState<boolean | null>(null)
  useEffect(() => { fetch('/graph.html', { method: 'HEAD' }).then(r => setOk(r.ok)).catch(() => setOk(false)) }, [])

  return (
    <div className="p-6">
      <PageHeader title="Graph Memory"
        subtitle="graphify knowledge graph — every node, edge, and community of the whole repo"
        actions={<a href="/graph.html" target="_blank" rel="noreferrer" className="text-xs px-3 py-1.5 rounded-lg bg-surface-container border border-outline/30 hover:border-primary">open full screen ↗</a>} />

      {ok === false ? (
        <div className="mt-6 rounded-xl border border-outline/20 bg-surface-container-low p-6 text-sm text-on-surface-variant">
          The graph isn’t published yet. Generate and publish it:
          <pre className="mt-3 text-xs bg-surface-container rounded-lg p-3 overflow-auto">{`# in the repo (code is free/local; add --backend claude-cli for docs):
GRAPHIFY_VIZ_NODE_LIMIT=9000 graphify cluster-only . --no-label
bash cli/graph-sync.sh    # copies graph.html + graph.json → dashboard/public/`}</pre>
        </div>
      ) : (
        <div className="mt-4 rounded-2xl border border-outline/20 overflow-hidden" style={{ height: 'calc(100vh - 190px)', background: '#07080e' }}>
          <iframe src="/graph.html" title="graphify graph" className="w-full h-full block" style={{ border: 0 }} />
        </div>
      )}

      <p className="mt-3 text-[11px] text-on-surface-variant/70">
        Live from graphify: 7.4k+ nodes · 415 communities (code today; run <code>graphify cluster-only . --backend claude-cli</code> to fold in the 866 docs). Regenerate on change via <code>graphify hook install</code> (auto-rebuild on commit).
      </p>
    </div>
  )
}
